name: laravel_sanctum_dart
description: A high-performance, feature-rich Dart package for Laravel Sanctum authentication with support for API tokens, SPA authentication, and advanced features like token abilities and automatic request handling.
version: 1.0.0
homepage: https://github.com/Kemerd/laravel_sanctum_dart
repository: https://github.com/Kemerd/laravel_sanctum_dart
issue_tracker: https://github.com/Kemerd/laravel_sanctum_dart/issues
documentation: https://pub.dev/packages/laravel_sanctum_dart

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  # HTTP client with interceptors and connection pooling
  dio: ^5.4.0

  # Secure storage for tokens
  flutter_secure_storage: ^9.0.0

  # JSON serialization
  json_annotation: ^4.9.0

  # Logging
  logger: ^2.0.2+1

  # Reactive state management
  rxdart: ^0.27.7

  # Cookie management
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1

  # Utilities
  meta: ^1.10.0

  flutter:
    sdk: flutter

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
  test: ^1.24.9
  mockito: ^5.4.4

  # Code generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

  # Linting
  flutter_lints: ^3.0.1

  # Coverage
  coverage: ^1.7.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages

# The following section is optional and is used to configure
# the behavior of the package linter.
flutter_lints:
  enable: true

topics:
  - laravel
  - sanctum
  - authentication
  - api
  - flutter
  - dart
  - http
  - tokens
  - spa

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: